# Use a compatible Node.js version for Next.js
FROM node:20.0.0-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Use a smaller base image for the final build
FROM node:20.0.0-alpine AS final

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "start"]