services:
  # Next.js landing app

  landing:
    build: .

    container_name: nextjs-landing

    ports:
      - "${NEXTJS_PORT:-9000}:3000"

    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

    networks:
      - portfolio-network

  # Nginx reverse proxy

  nginx:
    image: nginx:latest

    container_name: nginx

    ports:
      - "${NGINX_HTTP_PORT:-81}:80"

      - "${NGINX_HTTPS_PORT:-443}:443"

    volumes:
      - ./nginx:/etc/nginx/conf.d

      - ./ssl:/etc/nginx/ssl

    depends_on:

      - landing

    networks:
      - portfolio-network

volumes:
  db_datav2:

networks:
  portfolio-network:
    driver: bridge
