services:
  web:
    build: .
    ports:
      - '3002:3002'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"