services:
  web:
    image: node:16
    container_name: aet_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3003:3003"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

