import type { Metadata } from "next";
import "./globals.css";
import "boxicons/css/boxicons.min.css";

export const metadata: Metadata = {
  title: "AdFlow",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/images/adflow_logo.png",
        href: "/images/adflow_favicon-removebg-preview.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/images/adflow_logo.png",
        href: "/images/adflow_favicon-removebg-preview.png",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
